"""
ledger.py
---------
Phase 4: appends matched roles to a Markdown file you can scan asynchronously.

The file is created with a header on first run and only appended to thereafter.
Every entry is self-contained so you can copy-paste a single block into your
notes app or email client without context.
"""

import logging
from datetime import datetime
from pathlib import Path

from models import Job

log = logging.getLogger(__name__)

LEDGER_HEADER = """# Application Pipeline Ledger

Generated by the autonomous job-application pipeline.
Entries below were matched by the Gemini evaluator and synthesised for review.

"""

ENTRY_TEMPLATE = """## {title} - {company}

- **Location:** {location}
- **Posted:** {posted_at}
- **Due Date:** {due_date}
- **Apply:** [{url_label}]({apply_url})
- **Source:** {source}
- **Processed:** {processed_at}

### Executive Summary

{summary}

### Drafted Cover Letter

{letter}

---

"""


class Ledger:
    def __init__(self, path: str):
        self.path = Path(path)
        if not self.path.exists():
            self.path.write_text(LEDGER_HEADER, encoding="utf-8")

    def append(self, job: Job, summary: str, letter: str) -> None:
        entry = ENTRY_TEMPLATE.format(
            title=job.title,
            company=job.company,
            location=job.location or "(not specified)",
            posted_at=job.posted_at or "(unknown)",
            due_date=job.due_date or "(not stated)",
            url_label="Application Link" if job.apply_url else "(no link provided)",
            apply_url=job.apply_url or "#",
            source=job.source,
            processed_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
            summary=summary or "(no summary returned)",
            letter=letter or "(no letter returned)",
        )
        with self.path.open("a", encoding="utf-8") as f:
            f.write(entry)
        log.info("  Wrote entry for %s @ %s", job.title, job.company)
